# Generated by Django 5.2.8 on 2025-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('price', models.FloatField()),
                ('stockquantity', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.CharField()),
                ('maximum_retail_price', models.IntegerField()),
            ],
        ),
    ]
